polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns=[
  path('',views.index,name='index'),
  path('<int:question_id>/',views.detail,name='detail'),
  path('<int:question_id>/result/',views.result,name='result')
  ]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/models.py
from django.db import models


class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField("date published")
  
  
  def __str__(self):
    return self.question_text
  
class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=100)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

polls/views.py
from django.shortcuts import render

from .models import Question,Choice

def index(request):
  latest_question_list = Question.objects.order_by('-pub_date')[:5]
  context = {'latest_question_list': latest_question_list}
  return render(request,'polls/index.html', context)
  

def detail(request, question_id):
  try:
    question = Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404('question does not exist')
  return render(request, 'result.html',{'question':question})
  
  
def result(request, question_id):
  question = get_object_or_404(question, question_id)
  return render(request, 'result.html',{'question':question})

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pollster {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content%}
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center mb-3">Poll Questions</h1>
  {% if latest_question_list %}
  {% for question in latest_question_list %}
  <div class="card mb-3">
    <div class="card-body">
      <p class="lead">{{ question.question_text }}</p>
      <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote now</a>
      <a href="{% url 'polls:result' question.id %}" class="btn btn-secondary btn-sm">Results</a>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <p>no polls available</p>
  {% endif%}
{% endblock %}

polls/templates/polls/result.html
{% extends 'base.html' %}

{% block content%}
{% endblock %}